export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          slug: string;
          category: string;
          website_url: string | null;
          description: string | null;
          country: string | null;
          region: string | null;
          city: string | null;
          target_customers: string | null;
          website_scan_status: string;
          website_scanned_at: string | null;
          website_knowledge: Json;
          brain_completeness: number;
          brain_completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          category: string;
          website_url?: string | null;
          description?: string | null;
          country?: string | null;
          region?: string | null;
          city?: string | null;
          target_customers?: string | null;
          website_scan_status?: string;
          website_scanned_at?: string | null;
          website_knowledge?: Json;
          brain_completeness?: number;
          brain_completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          category?: string;
          website_url?: string | null;
          description?: string | null;
          country?: string | null;
          region?: string | null;
          city?: string | null;
          target_customers?: string | null;
          website_scan_status?: string;
          website_scanned_at?: string | null;
          website_knowledge?: Json;
          brain_completeness?: number;
          brain_completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_members: {
        Row: {
          id: string;
          business_id: string;
          user_id: string;
          role: "owner" | "admin" | "member";
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id: string;
          role?: "owner" | "admin" | "member";
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string;
          role?: "owner" | "admin" | "member";
          created_at?: string;
        };
      };
      business_products: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string | null;
          url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description?: string | null;
          url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string | null;
          url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_goals: {
        Row: {
          id: string;
          business_id: string;
          goal: string;
          is_primary: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          goal: string;
          is_primary?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          goal?: string;
          is_primary?: boolean;
          created_at?: string;
        };
      };
      brand_profiles: {
        Row: {
          id: string;
          business_id: string;
          tone: string;
          style_description: string | null;
          avoid_words: string | null;
          tagline: string | null;
          brand_keywords: string[];
          preferred_phrases: string[];
          forbidden_phrases: string[];
          emoji_preference: string;
          hashtag_preference: string;
          writing_length: string;
          language_preferences: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          tone: string;
          style_description?: string | null;
          avoid_words?: string | null;
          tagline?: string | null;
          brand_keywords?: string[];
          preferred_phrases?: string[];
          forbidden_phrases?: string[];
          emoji_preference?: string;
          hashtag_preference?: string;
          writing_length?: string;
          language_preferences?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          tone?: string;
          style_description?: string | null;
          avoid_words?: string | null;
          tagline?: string | null;
          brand_keywords?: string[];
          preferred_phrases?: string[];
          forbidden_phrases?: string[];
          emoji_preference?: string;
          hashtag_preference?: string;
          writing_length?: string;
          language_preferences?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_policies: {
        Row: {
          id: string;
          business_id: string;
          autonomy_level: "assistant" | "manager";
          require_approval_discount: boolean;
          require_approval_refund: boolean;
          require_approval_complaint: boolean;
          require_approval_pricing: boolean;
          require_approval_legal: boolean;
          require_approval_medical: boolean;
          require_approval_partnership: boolean;
          require_approval_promises: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          autonomy_level?: "assistant" | "manager";
          require_approval_discount?: boolean;
          require_approval_refund?: boolean;
          require_approval_complaint?: boolean;
          require_approval_pricing?: boolean;
          require_approval_legal?: boolean;
          require_approval_medical?: boolean;
          require_approval_partnership?: boolean;
          require_approval_promises?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          autonomy_level?: "assistant" | "manager";
          require_approval_discount?: boolean;
          require_approval_refund?: boolean;
          require_approval_complaint?: boolean;
          require_approval_pricing?: boolean;
          require_approval_legal?: boolean;
          require_approval_medical?: boolean;
          require_approval_partnership?: boolean;
          require_approval_promises?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          business_id: string;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          business_id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          severity: "info" | "warning" | "error" | "success";
          read: boolean;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          severity?: "info" | "warning" | "error" | "success";
          read?: boolean;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          message?: string;
          severity?: "info" | "warning" | "error" | "success";
          read?: boolean;
          metadata?: Json;
          created_at?: string;
        };
      };
      business_services: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string | null;
          price_text: string | null;
          price_visibility: string;
          url: string | null;
          source_type: string;
          approval_status: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description?: string | null;
          price_text?: string | null;
          price_visibility?: string;
          url?: string | null;
          source_type?: string;
          approval_status?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string | null;
          price_text?: string | null;
          price_visibility?: string;
          url?: string | null;
          source_type?: string;
          approval_status?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_facts: {
        Row: {
          id: string;
          business_id: string;
          category: string;
          title: string;
          content: string;
          priority: number;
          source_type: string;
          approval_status: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          category?: string;
          title: string;
          content: string;
          priority?: number;
          source_type?: string;
          approval_status?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          category?: string;
          title?: string;
          content?: string;
          priority?: number;
          source_type?: string;
          approval_status?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_faqs: {
        Row: {
          id: string;
          business_id: string;
          question: string;
          answer: string;
          category: string;
          priority: number;
          source_type: string;
          approval_status: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          question: string;
          answer: string;
          category?: string;
          priority?: number;
          source_type?: string;
          approval_status?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          question?: string;
          answer?: string;
          category?: string;
          priority?: number;
          source_type?: string;
          approval_status?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_locations: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          address: string | null;
          city: string | null;
          region: string | null;
          country: string | null;
          postal_code: string | null;
          phone: string | null;
          opening_hours: Json;
          service_area: string | null;
          is_primary: boolean;
          is_active: boolean;
          source_type: string;
          approval_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          address?: string | null;
          city?: string | null;
          region?: string | null;
          country?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          opening_hours?: Json;
          service_area?: string | null;
          is_primary?: boolean;
          is_active?: boolean;
          source_type?: string;
          approval_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          address?: string | null;
          city?: string | null;
          region?: string | null;
          country?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          opening_hours?: Json;
          service_area?: string | null;
          is_primary?: boolean;
          is_active?: boolean;
          source_type?: string;
          approval_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_offers: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string;
          offer_type: string;
          discount_text: string | null;
          start_at: string | null;
          end_at: string | null;
          terms: string | null;
          url: string | null;
          is_active: boolean;
          source_type: string;
          approval_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description: string;
          offer_type?: string;
          discount_text?: string | null;
          start_at?: string | null;
          end_at?: string | null;
          terms?: string | null;
          url?: string | null;
          is_active?: boolean;
          source_type?: string;
          approval_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string;
          offer_type?: string;
          discount_text?: string | null;
          start_at?: string | null;
          end_at?: string | null;
          terms?: string | null;
          url?: string | null;
          is_active?: boolean;
          source_type?: string;
          approval_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      customer_personas: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string | null;
          pain_points: string | null;
          needs: string | null;
          buying_triggers: string | null;
          objections: string | null;
          preferred_channels: string | null;
          priority: number;
          is_active: boolean;
          source_type: string;
          approval_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description?: string | null;
          pain_points?: string | null;
          needs?: string | null;
          buying_triggers?: string | null;
          objections?: string | null;
          preferred_channels?: string | null;
          priority?: number;
          is_active?: boolean;
          source_type?: string;
          approval_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string | null;
          pain_points?: string | null;
          needs?: string | null;
          buying_triggers?: string | null;
          objections?: string | null;
          preferred_channels?: string | null;
          priority?: number;
          is_active?: boolean;
          source_type?: string;
          approval_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_documents: {
        Row: {
          id: string;
          business_id: string;
          title: string;
          description: string | null;
          document_type: string;
          source_type: string;
          content: string | null;
          source_url: string | null;
          approval_status: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          title: string;
          description?: string | null;
          document_type?: string;
          source_type?: string;
          content?: string | null;
          source_url?: string | null;
          approval_status?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          title?: string;
          description?: string | null;
          document_type?: string;
          source_type?: string;
          content?: string | null;
          source_url?: string | null;
          approval_status?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      business_interviews: {
        Row: {
          id: string;
          business_id: string;
          status: string;
          current_stage: string;
          completion_percentage: number;
          knowledge_extracted: Json;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          business_id: string;
          status?: string;
          current_stage?: string;
          completion_percentage?: number;
          knowledge_extracted?: Json;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          business_id?: string;
          status?: string;
          current_stage?: string;
          completion_percentage?: number;
          knowledge_extracted?: Json;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
      };
      business_interview_messages: {
        Row: {
          id: string;
          interview_id: string;
          role: string;
          content: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          interview_id: string;
          role: string;
          content: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          interview_id?: string;
          role?: string;
          content?: string;
          metadata?: Json;
          created_at?: string;
        };
      };
      knowledge_pending: {
        Row: {
          id: string;
          business_id: string;
          entity_type: string;
          entity_id: string | null;
          data: Json;
          source_type: string;
          confidence: number;
          approval_status: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          entity_type: string;
          entity_id?: string | null;
          data: Json;
          source_type?: string;
          confidence?: number;
          approval_status?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          entity_type?: string;
          entity_id?: string | null;
          data?: Json;
          source_type?: string;
          confidence?: number;
          approval_status?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
      };
      social_conversations: {
        Row: {
          id: string;
          business_id: string;
          social_account_id: string;
          platform: string;
          platform_conversation_id: string | null;
          channel_type: string;
          customer_platform_id: string | null;
          customer_name: string | null;
          customer_username: string | null;
          status: string;
          priority: string;
          intent: string | null;
          intent_confidence: number | null;
          risk_level: string;
          matched_persona_id: string | null;
          persona_confidence: number | null;
          summary: string | null;
          ai_handled: boolean;
          human_locked: boolean;
          ai_locked_until: string | null;
          unread_count: number;
          last_message_at: string | null;
          last_inbound_at: string | null;
          last_outbound_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          social_account_id: string;
          platform: string;
          platform_conversation_id?: string | null;
          channel_type?: string;
          customer_platform_id?: string | null;
          customer_name?: string | null;
          customer_username?: string | null;
          status?: string;
          priority?: string;
          intent?: string | null;
          intent_confidence?: number | null;
          risk_level?: string;
          matched_persona_id?: string | null;
          persona_confidence?: number | null;
          summary?: string | null;
          ai_handled?: boolean;
          human_locked?: boolean;
          ai_locked_until?: string | null;
          unread_count?: number;
          last_message_at?: string | null;
          last_inbound_at?: string | null;
          last_outbound_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          social_account_id?: string;
          platform?: string;
          platform_conversation_id?: string | null;
          channel_type?: string;
          customer_platform_id?: string | null;
          customer_name?: string | null;
          customer_username?: string | null;
          status?: string;
          priority?: string;
          intent?: string | null;
          intent_confidence?: number | null;
          risk_level?: string;
          matched_persona_id?: string | null;
          persona_confidence?: number | null;
          summary?: string | null;
          ai_handled?: boolean;
          human_locked?: boolean;
          ai_locked_until?: string | null;
          unread_count?: number;
          last_message_at?: string | null;
          last_inbound_at?: string | null;
          last_outbound_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      social_messages: {
        Row: {
          id: string;
          conversation_id: string;
          platform_message_id: string | null;
          direction: string;
          sender_type: string;
          sender_platform_id: string | null;
          sender_name: string | null;
          text: string | null;
          media_metadata: any;
          ai_classified: boolean;
          ai_intent: string | null;
          ai_confidence: number | null;
          raw_data: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          platform_message_id?: string | null;
          direction: string;
          sender_type: string;
          sender_platform_id?: string | null;
          sender_name?: string | null;
          text?: string | null;
          media_metadata?: any;
          ai_classified?: boolean;
          ai_intent?: string | null;
          ai_confidence?: number | null;
          raw_data?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          platform_message_id?: string | null;
          direction?: string;
          sender_type?: string;
          sender_platform_id?: string | null;
          sender_name?: string | null;
          text?: string | null;
          media_metadata?: any;
          ai_classified?: boolean;
          ai_intent?: string | null;
          ai_confidence?: number | null;
          raw_data?: any;
          created_at?: string;
        };
      };
      community_approvals: {
        Row: {
          id: string;
          conversation_id: string;
          message_id: string | null;
          action_type: string;
          draft_response: string;
          reason: string | null;
          risk_level: string;
          confidence: number | null;
          status: string;
          edited_response: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          message_id?: string | null;
          action_type: string;
          draft_response: string;
          reason?: string | null;
          risk_level?: string;
          confidence?: number | null;
          status?: string;
          edited_response?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          message_id?: string | null;
          action_type?: string;
          draft_response?: string;
          reason?: string | null;
          risk_level?: string;
          confidence?: number | null;
          status?: string;
          edited_response?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      community_action_jobs: {
        Row: {
          id: string;
          conversation_id: string;
          message_id: string | null;
          approval_id: string | null;
          action_type: string;
          status: string;
          attempt_count: number;
          max_attempts: number;
          last_error: string | null;
          error_type: string | null;
          provider_message_id: string | null;
          idempotency_key: string | null;
          response_text: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          message_id?: string | null;
          approval_id?: string | null;
          action_type: string;
          status?: string;
          attempt_count?: number;
          max_attempts?: number;
          last_error?: string | null;
          error_type?: string | null;
          provider_message_id?: string | null;
          idempotency_key?: string | null;
          response_text?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          message_id?: string | null;
          approval_id?: string | null;
          action_type?: string;
          status?: string;
          attempt_count?: number;
          max_attempts?: number;
          last_error?: string | null;
          error_type?: string | null;
          provider_message_id?: string | null;
          idempotency_key?: string | null;
          response_text?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversation_notes: {
        Row: {
          id: string;
          conversation_id: string;
          note: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          note: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          note?: string;
          created_by?: string | null;
          created_at?: string;
        };
      };
    };
    social_accounts: {
      Row: {
        id: string;
        business_id: string;
        platform: string;
        platform_account_id: string;
        account_name: string | null;
        username: string | null;
        account_type: string | null;
        profile_url: string | null;
        profile_image_url: string | null;
        status: string;
        connection_status: string;
        last_sync_started_at: string | null;
        last_synced_at: string | null;
        last_successful_sync_at: string | null;
        last_sync_error: string | null;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        platform: string;
        platform_account_id: string;
        account_name?: string | null;
        username?: string | null;
        account_type?: string | null;
        profile_url?: string | null;
        profile_image_url?: string | null;
        status?: string;
        connection_status?: string;
        last_sync_started_at?: string | null;
        last_synced_at?: string | null;
        last_successful_sync_at?: string | null;
        last_sync_error?: string | null;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        platform?: string;
        platform_account_id?: string;
        account_name?: string | null;
        username?: string | null;
        account_type?: string | null;
        profile_url?: string | null;
        profile_image_url?: string | null;
        status?: string;
        connection_status?: string;
        last_sync_started_at?: string | null;
        last_synced_at?: string | null;
        last_successful_sync_at?: string | null;
        last_sync_error?: string | null;
        created_at?: string;
        updated_at?: string;
      };
    };
    social_account_credentials: {
      Row: {
        id: string;
        social_account_id: string;
        access_token_encrypted: string;
        refresh_token_encrypted: string | null;
        token_expires_at: string | null;
        scopes: string[] | null;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        social_account_id: string;
        access_token_encrypted: string;
        refresh_token_encrypted?: string | null;
        token_expires_at?: string | null;
        scopes?: string[] | null;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        social_account_id?: string;
        access_token_encrypted?: string;
        refresh_token_encrypted?: string | null;
        token_expires_at?: string | null;
        scopes?: string[] | null;
        created_at?: string;
        updated_at?: string;
      };
    };
    social_account_links: {
      Row: {
        id: string;
        business_id: string;
        parent_account_id: string;
        child_account_id: string;
        relationship_type: string;
        created_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        parent_account_id: string;
        child_account_id: string;
        relationship_type: string;
        created_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        parent_account_id?: string;
        child_account_id?: string;
        relationship_type?: string;
        created_at?: string;
      };
    };
    oauth_states: {
      Row: {
        id: string;
        user_id: string;
        business_id: string;
        provider: string;
        state_hash: string;
        expires_at: string;
        used: boolean;
        created_at: string;
      };
      Insert: {
        id?: string;
        user_id: string;
        business_id: string;
        provider: string;
        state_hash: string;
        expires_at: string;
        used?: boolean;
        created_at?: string;
      };
      Update: {
        id?: string;
        user_id?: string;
        business_id?: string;
        provider?: string;
        state_hash?: string;
        expires_at?: string;
        used?: boolean;
        created_at?: string;
      };
    };
    social_posts: {
      Row: {
        id: string;
        social_account_id: string;
        platform_post_id: string;
        post_type: string | null;
        caption: string | null;
        permalink: string | null;
        published_at: string | null;
        media_url: string | null;
        thumbnail_url: string | null;
        raw_data: Json;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        social_account_id: string;
        platform_post_id: string;
        post_type?: string | null;
        caption?: string | null;
        permalink?: string | null;
        published_at?: string | null;
        media_url?: string | null;
        thumbnail_url?: string | null;
        raw_data?: Json;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        social_account_id?: string;
        platform_post_id?: string;
        post_type?: string | null;
        caption?: string | null;
        permalink?: string | null;
        published_at?: string | null;
        media_url?: string | null;
        thumbnail_url?: string | null;
        raw_data?: Json;
        created_at?: string;
        updated_at?: string;
      };
    };
    social_comments: {
      Row: {
        id: string;
        social_account_id: string;
        social_post_id: string;
        platform_comment_id: string;
        parent_platform_comment_id: string | null;
        author_platform_id: string | null;
        author_name: string | null;
        text: string | null;
        created_at: string;
        updated_at: string;
        raw_data: Json;
      };
      Insert: {
        id?: string;
        social_account_id: string;
        social_post_id: string;
        platform_comment_id: string;
        parent_platform_comment_id?: string | null;
        author_platform_id?: string | null;
        author_name?: string | null;
        text?: string | null;
        created_at?: string;
        updated_at?: string;
        raw_data?: Json;
      };
      Update: {
        id?: string;
        social_account_id?: string;
        social_post_id?: string;
        platform_comment_id?: string;
        parent_platform_comment_id?: string | null;
        author_platform_id?: string | null;
        author_name?: string | null;
        text?: string | null;
        created_at?: string;
        updated_at?: string;
        raw_data?: Json;
      };
    };
    social_account_metrics: {
      Row: {
        id: string;
        social_account_id: string;
        metric_date: string;
        followers_count: number | null;
        following_count: number | null;
        posts_count: number | null;
        raw_data: Json;
        created_at: string;
      };
      Insert: {
        id?: string;
        social_account_id: string;
        metric_date: string;
        followers_count?: number | null;
        following_count?: number | null;
        posts_count?: number | null;
        raw_data?: Json;
        created_at?: string;
      };
      Update: {
        id?: string;
        social_account_id?: string;
        metric_date?: string;
        followers_count?: number | null;
        following_count?: number | null;
        posts_count?: number | null;
        raw_data?: Json;
        created_at?: string;
      };
    };
    social_sync_jobs: {
      Row: {
        id: string;
        business_id: string;
        social_account_id: string;
        sync_type: string;
        status: string;
        progress: Json;
        items_found: number;
        items_processed: number;
        error: string | null;
        started_at: string | null;
        completed_at: string | null;
        created_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        social_account_id: string;
        sync_type: string;
        status?: string;
        progress?: Json;
        items_found?: number;
        items_processed?: number;
        error?: string | null;
        started_at?: string | null;
        completed_at?: string | null;
        created_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        social_account_id?: string;
        sync_type?: string;
        status?: string;
        progress?: Json;
        items_found?: number;
        items_processed?: number;
        error?: string | null;
        started_at?: string | null;
        completed_at?: string | null;
        created_at?: string;
      };
    };
    social_observations: {
      Row: {
        id: string;
        business_id: string;
        social_account_id: string | null;
        observation_type: string;
        severity: string;
        title: string;
        summary: string;
        evidence: Json;
        source_ids: Json;
        confidence: number;
        status: string;
        signature: string | null;
        expires_at: string | null;
        created_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        social_account_id?: string | null;
        observation_type: string;
        severity?: string;
        title: string;
        summary: string;
        evidence?: Json;
        source_ids?: Json;
        confidence?: number;
        status?: string;
        signature?: string | null;
        expires_at?: string | null;
        created_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        social_account_id?: string | null;
        observation_type?: string;
        severity?: string;
        title?: string;
        summary?: string;
        evidence?: Json;
        source_ids?: Json;
        confidence?: number;
        status?: string;
        signature?: string | null;
        expires_at?: string | null;
        created_at?: string;
      };
    };
    social_recommendations: {
      Row: {
        id: string;
        business_id: string;
        observation_id: string | null;
        title: string;
        description: string;
        action_type: string;
        priority: string;
        confidence: number;
        reason: string;
        status: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        observation_id?: string | null;
        title: string;
        description: string;
        action_type: string;
        priority?: string;
        confidence?: number;
        reason: string;
        status?: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        observation_id?: string | null;
        title?: string;
        description?: string;
        action_type?: string;
        priority?: string;
        confidence?: number;
        reason?: string;
        status?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
    social_content_classifications: {
      Row: {
        id: string;
        business_id: string;
        social_account_id: string;
        social_post_id: string;
        pillar: string | null;
        objective: string | null;
        audience: string | null;
        format: string | null;
        product: string | null;
        cta: string | null;
        promotional: boolean;
        confidence: number;
        raw_classification: Json;
        created_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        social_account_id: string;
        social_post_id: string;
        pillar?: string | null;
        objective?: string | null;
        audience?: string | null;
        format?: string | null;
        product?: string | null;
        cta?: string | null;
        promotional?: boolean;
        confidence?: number;
        raw_classification?: Json;
        created_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        social_account_id?: string;
        social_post_id?: string;
        pillar?: string | null;
        objective?: string | null;
        audience?: string | null;
        format?: string | null;
        product?: string | null;
        cta?: string | null;
        promotional?: boolean;
        confidence?: number;
        raw_classification?: Json;
        created_at?: string;
      };
    };
    social_leads: {
      Row: {
        id: string;
        business_id: string;
        social_account_id: string;
        platform_user_id: string;
        name: string | null;
        username: string | null;
        source_type: string;
        source_reference: string | null;
        source_conversation_id: string | null;
        source_message_ids: string[];
        observation_ids: string[];
        intent: string;
        reason: string;
        status: string;
        stage: string | null;
        confidence: number;
        interested_product_id: string | null;
        interested_service_id: string | null;
        requirement: string | null;
        quantity: string | null;
        location: string | null;
        estimated_value: number | null;
        estimated_value_currency: string;
        assigned_to: string | null;
        next_action: string | null;
        next_action_at: string | null;
        notes: string | null;
        tags: string[];
        brain_version: number | null;
        first_detected_at: string;
        last_activity_at: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        social_account_id: string;
        platform_user_id: string;
        name?: string | null;
        username?: string | null;
        source_type: string;
        source_reference?: string | null;
        source_conversation_id?: string | null;
        source_message_ids?: string[];
        observation_ids?: string[];
        intent: string;
        reason: string;
        status?: string;
        stage?: string | null;
        confidence?: number;
        interested_product_id?: string | null;
        interested_service_id?: string | null;
        requirement?: string | null;
        quantity?: string | null;
        location?: string | null;
        estimated_value?: number | null;
        estimated_value_currency?: string;
        assigned_to?: string | null;
        next_action?: string | null;
        next_action_at?: string | null;
        notes?: string | null;
        tags?: string[];
        brain_version?: number | null;
        first_detected_at?: string;
        last_activity_at?: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        social_account_id?: string;
        platform_user_id?: string;
        name?: string | null;
        username?: string | null;
        source_type?: string;
        source_reference?: string | null;
        source_conversation_id?: string | null;
        source_message_ids?: string[];
        observation_ids?: string[];
        intent?: string;
        reason?: string;
        status?: string;
        stage?: string | null;
        confidence?: number;
        interested_product_id?: string | null;
        interested_service_id?: string | null;
        requirement?: string | null;
        quantity?: string | null;
        location?: string | null;
        estimated_value?: number | null;
        estimated_value_currency?: string;
        assigned_to?: string | null;
        next_action?: string | null;
        next_action_at?: string | null;
        notes?: string | null;
        tags?: string[];
        brain_version?: number | null;
        first_detected_at?: string;
        last_activity_at?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
    lead_follow_ups: {
      Row: {
        id: string;
        lead_id: string;
        type: string;
        due_at: string;
        status: string;
        message_draft: string | null;
        created_by: string | null;
        completed_by: string | null;
        created_at: string;
        completed_at: string | null;
      };
      Insert: {
        id?: string;
        lead_id: string;
        type: string;
        due_at: string;
        status?: string;
        message_draft?: string | null;
        created_by?: string | null;
        completed_by?: string | null;
        created_at?: string;
        completed_at?: string | null;
      };
      Update: {
        id?: string;
        lead_id?: string;
        type?: string;
        due_at?: string;
        status?: string;
        message_draft?: string | null;
        created_by?: string | null;
        completed_by?: string | null;
        created_at?: string;
        completed_at?: string | null;
      };
    };
    social_interactions: {
      Row: {
        id: string;
        business_id: string;
        social_account_id: string;
        social_comment_id: string | null;
        platform_user_id: string | null;
        user_name: string | null;
        interaction_type: string;
        classification: string;
        confidence: number;
        reason: string | null;
        priority: string;
        raw_data: Json;
        created_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        social_account_id: string;
        social_comment_id?: string | null;
        platform_user_id?: string | null;
        user_name?: string | null;
        interaction_type: string;
        classification: string;
        confidence?: number;
        reason?: string | null;
        priority?: string;
        raw_data?: Json;
        created_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        social_account_id?: string;
        social_comment_id?: string | null;
        platform_user_id?: string | null;
        user_name?: string | null;
        interaction_type?: string;
        classification?: string;
        confidence?: number;
        reason?: string | null;
        priority?: string;
        raw_data?: Json;
        created_at?: string;
      };
    };
    social_scan_jobs: {
      Row: {
        id: string;
        business_id: string;
        scan_type: string;
        status: string;
        observations_created: number;
        recommendations_created: number;
        leads_created: number;
        error: string | null;
        started_at: string | null;
        completed_at: string | null;
        created_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        scan_type: string;
        status?: string;
        observations_created?: number;
        recommendations_created?: number;
        leads_created?: number;
        error?: string | null;
        started_at?: string | null;
        completed_at?: string | null;
        created_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        scan_type?: string;
        status?: string;
        observations_created?: number;
        recommendations_created?: number;
        leads_created?: number;
        error?: string | null;
        started_at?: string | null;
        completed_at?: string | null;
        created_at?: string;
      };
    };
    content_items: {
      Row: {
        id: string;
        business_id: string;
        platform: string;
        type: string;
        title: string;
        topic: string;
        objective: string;
        pillar: string;
        persona_id: string | null;
        persona_name: string | null;
        status: string;
        caption: string | null;
        creative_brief: string | null;
        script: string | null;
        hook: string | null;
        cta: string | null;
        hashtags: string[] | null;
        source_observation_ids: string[] | null;
        strategy_version: number | null;
        brain_version: number | null;
        strategy_override: boolean;
        quality_score: number | null;
        quality_status: string | null;
        validation_result: Json;
        review_result: Json;
        metadata: Json;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        business_id: string;
        platform: string;
        type: string;
        title: string;
        topic: string;
        objective: string;
        pillar: string;
        persona_id?: string | null;
        persona_name?: string | null;
        status?: string;
        caption?: string | null;
        creative_brief?: string | null;
        script?: string | null;
        hook?: string | null;
        cta?: string | null;
        hashtags?: string[] | null;
        source_observation_ids?: string[] | null;
        strategy_version?: number | null;
        brain_version?: number | null;
        strategy_override?: boolean;
        quality_score?: number | null;
        quality_status?: string | null;
        validation_result?: Json;
        review_result?: Json;
        metadata?: Json;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        business_id?: string;
        platform?: string;
        type?: string;
        title?: string;
        topic?: string;
        objective?: string;
        pillar?: string;
        persona_id?: string | null;
        persona_name?: string | null;
        status?: string;
        caption?: string | null;
        creative_brief?: string | null;
        script?: string | null;
        hook?: string | null;
        cta?: string | null;
        hashtags?: string[] | null;
        source_observation_ids?: string[] | null;
        strategy_version?: number | null;
        brain_version?: number | null;
        strategy_override?: boolean;
        quality_score?: number | null;
        quality_status?: string | null;
        validation_result?: Json;
        review_result?: Json;
        metadata?: Json;
        created_at?: string;
        updated_at?: string;
      };
    };
    content_versions: {
      Row: {
        id: string;
        content_item_id: string;
        version: number;
        caption: string | null;
        creative_brief: string | null;
        script: string | null;
        hook: string | null;
        cta: string | null;
        changes_summary: string | null;
        created_by: string;
        created_at: string;
      };
      Insert: {
        id?: string;
        content_item_id: string;
        version: number;
        caption?: string | null;
        creative_brief?: string | null;
        script?: string | null;
        hook?: string | null;
        cta?: string | null;
        changes_summary?: string | null;
        created_by?: string;
        created_at?: string;
      };
      Update: {
        id?: string;
        content_item_id?: string;
        version?: number;
        caption?: string | null;
        creative_brief?: string | null;
        script?: string | null;
        hook?: string | null;
        cta?: string | null;
        changes_summary?: string | null;
        created_by?: string;
        created_at?: string;
      };
    };
      content_plans: {
        Row: {
          id: string;
          business_id: string;
          title: string;
          date_from: string;
          date_to: string;
          platform: string | null;
          items: Json;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          title: string;
          date_from: string;
          date_to: string;
          platform?: string | null;
          items?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          title?: string;
          date_from?: string;
          date_to?: string;
          platform?: string | null;
          items?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      content_schedules: {
        Row: {
          id: string;
          content_item_id: string;
          social_account_id: string;
          scheduled_at: string;
          scheduled_at_utc: string;
          timezone: string;
          status: string;
          provider: string | null;
          provider_post_id: string | null;
          published_at: string | null;
          failure_reason: string | null;
          retry_count: number;
          max_retries: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          content_item_id: string;
          social_account_id: string;
          scheduled_at: string;
          scheduled_at_utc: string;
          timezone?: string;
          status?: string;
          provider?: string | null;
          provider_post_id?: string | null;
          published_at?: string | null;
          failure_reason?: string | null;
          retry_count?: number;
          max_retries?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          content_item_id?: string;
          social_account_id?: string;
          scheduled_at?: string;
          scheduled_at_utc?: string;
          timezone?: string;
          status?: string;
          provider?: string | null;
          provider_post_id?: string | null;
          published_at?: string | null;
          failure_reason?: string | null;
          retry_count?: number;
          max_retries?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      content_publish_jobs: {
        Row: {
          id: string;
          content_schedule_id: string;
          content_item_id: string;
          social_account_id: string;
          status: string;
          attempt_count: number;
          max_attempts: number;
          last_error: string | null;
          error_type: string | null;
          provider_post_id: string | null;
          idempotency_key: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          content_schedule_id: string;
          content_item_id: string;
          social_account_id: string;
          status?: string;
          attempt_count?: number;
          max_attempts?: number;
          last_error?: string | null;
          error_type?: string | null;
          provider_post_id?: string | null;
          idempotency_key?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          content_schedule_id?: string;
          content_item_id?: string;
          social_account_id?: string;
          status?: string;
          attempt_count?: number;
          max_attempts?: number;
          last_error?: string | null;
          error_type?: string | null;
          provider_post_id?: string | null;
          idempotency_key?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
};
};
  Enums: {
    member_role: "owner" | "admin" | "member";
    autonomy_level: "assistant" | "manager";
    notification_severity: "info" | "warning" | "error" | "success";
  };
};
}
}

export type Business = Database["public"]["Tables"]["businesses"]["Row"];
export type BusinessMember = Database["public"]["Tables"]["business_members"]["Row"];
export type BusinessProduct = Database["public"]["Tables"]["business_products"]["Row"];
export type BusinessGoal = Database["public"]["Tables"]["business_goals"]["Row"];
export type BrandProfile = Database["public"]["Tables"]["brand_profiles"]["Row"];
export type AiPolicy = Database["public"]["Tables"]["ai_policies"]["Row"];
export type AuditLog = Database["public"]["Tables"]["audit_logs"]["Row"];
export type Notification = Database["public"]["Tables"]["notifications"]["Row"];
export type BusinessService = Database["public"]["Tables"]["business_services"]["Row"];
export type BusinessFact = Database["public"]["Tables"]["business_facts"]["Row"];
export type BusinessFaq = Database["public"]["Tables"]["business_faqs"]["Row"];
export type BusinessLocation = Database["public"]["Tables"]["business_locations"]["Row"];
export type BusinessOffer = Database["public"]["Tables"]["business_offers"]["Row"];
export type CustomerPersona = Database["public"]["Tables"]["customer_personas"]["Row"];
export type BusinessDocument = Database["public"]["Tables"]["business_documents"]["Row"];
export type BusinessInterview = Database["public"]["Tables"]["business_interviews"]["Row"];
export type BusinessInterviewMessage = Database["public"]["Tables"]["business_interview_messages"]["Row"];
export type KnowledgePending = Database["public"]["Tables"]["knowledge_pending"]["Row"];
export type SocialAccount = Database["public"]["Tables"]["social_accounts"]["Row"];
export type SocialAccountCredential = Database["public"]["Tables"]["social_account_credentials"]["Row"];
export type SocialAccountLink = Database["public"]["Tables"]["social_account_links"]["Row"];
export type OAuthState = Database["public"]["Tables"]["oauth_states"]["Row"];
export type SocialPost = Database["public"]["Tables"]["social_posts"]["Row"];
export type SocialComment = Database["public"]["Tables"]["social_comments"]["Row"];
export type SocialAccountMetric = Database["public"]["Tables"]["social_account_metrics"]["Row"];
export type SocialSyncJob = Database["public"]["Tables"]["social_sync_jobs"]["Row"];
export type SocialObservation = Database["public"]["Tables"]["social_observations"]["Row"];
export type SocialRecommendation = Database["public"]["Tables"]["social_recommendations"]["Row"];
export type SocialContentClassification = Database["public"]["Tables"]["social_content_classifications"]["Row"];
export type SocialLead = Database["public"]["Tables"]["social_leads"]["Row"];
export type LeadFollowUp = Database["public"]["Tables"]["lead_follow_ups"]["Row"];
export type SocialInteraction = Database["public"]["Tables"]["social_interactions"]["Row"];
export type SocialScanJob = Database["public"]["Tables"]["social_scan_jobs"]["Row"];
export type ContentItem = Database["public"]["Tables"]["content_items"]["Row"];
export type ContentVersion = Database["public"]["Tables"]["content_versions"]["Row"];
export type ContentPlan = Database["public"]["Tables"]["content_plans"]["Row"];
export type ContentSchedule = Database["public"]["Tables"]["content_schedules"]["Row"];
export type ContentPublishJob = Database["public"]["Tables"]["content_publish_jobs"]["Row"];

export type MemberRole = "owner" | "admin" | "member";
export type AutonomyLevel = "assistant" | "manager";
export type NotificationSeverity = "info" | "warning" | "error" | "success";
